name: ESP32 Build CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Leggi versione firmware
        run: |
          FW_VERSION=$(cat version.txt)
          echo "FW_VERSION=$FW_VERSION" >> "$GITHUB_ENV"
          echo "[CI] FW_VERSION=$FW_VERSION"

      - name: Cache dipendenze e Toolchain PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Installazione PlatformIO CLI
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Compilazione Firmware
        run: pio run

      - name: Salva Artefatti (.bin)
        uses: actions/upload-artifact@v4
        with:
          name: sentinel-firmware-binaries
          path: |
            .pio/build/**/firmware.bin
            .pio/build/**/firmware_merged.bin
